name: Simple GitHub OIDC Test

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Get GitHub OIDC Token (Built-in)
        id: oidc
        uses: actions/github-script@v7
        with:
          script: |
            const token = await core.getIDToken('https://github.com/${{ github.repository }}');
            core.setSecret(token);
            core.setOutput('token', token);
            
            // Decode token for debugging
            const payload = JSON.parse(Buffer.from(token.split('.')[1], 'base64').toString());
            console.log('Token claims:', payload);
            
            return token;
      
      - name: Call Flask Server
        env:
          FLASK_TUNNEL_URL: ${{ secrets.FLASK_TUNNEL_URL }}
        run: |
          TOKEN="${{ steps.oidc.outputs.token }}"
          
          echo "Calling Flask server..."
          curl -H "Authorization: Bearer $TOKEN" "$FLASK_TUNNEL_URL/protected"
