name: Backend

on:
  push:
    branches:
    - main
    # paths:
    # - 'backend/requirements.txt'
    # - '.github/workflows/baseImage.yaml'
    # - 'deploy/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Rollout backend

    steps:
    - uses: actions/checkout@v3
    - name: Install sshpass
      run: |
          sudo apt-get update
          sudo apt-get install sshpass -y
    - name: Copy Files
      run: |
            sshpass -p "${{ secrets.SSH_PAS }}" scp -r -o StrictHostKeyChecking=no ./backend/* ${{ secrets.SSH_USER }}@${{secrets.SSH_HOST}}:${{ secrets.BASE_DIR_APP }}data