name: Base Image

on:
  push:
    branches:
    - main
    paths:
    - 'backend/requirements.txt'
    - '.github/workflows/baseImage.yaml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Base Image

    steps:
    - uses: actions/checkout@v3
    - name: Install sshpass
      run: |
          sudo apt-get update
          sudo apt-get install sshpass -y
    - name: Copy Docker Build
      run: |
            sshpass -p "${{ secrets.SSH_PAS }}" scp -r -o StrictHostKeyChecking=no ./backend/requirements.txt ./deploy/* ${{ secrets.SSH_USER }}@${{secrets.SSH_HOST}}:${{ secrets.BASE_DIR_APP }}build
    - name: Build Image
      run: |
            sshpass -p "${{ secrets.SSH_PAS }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{secrets.SSH_HOST}} << EOF
            ssh local << EOL
            cd ${{ secrets.BASE_DIR_APP }}build/ \
            && docker build . -t dj:latest
            EOL
            EOF