name: Base Image

on:
  push:
    branches:
    - main
    paths:
    - 'backend/requirements.txt'
    - '.github/workflows/baseImage.yaml'
    - 'deploy/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Base Image

    steps:
    - uses: actions/checkout@v3
    - name: Install sshpass
      run: |
          which rsync
          # sudo apt-get update
          # sudo apt-get install sshpass -y
    - name: Copy Docker Build
      run: |
            sshpass -p "${{ secrets.SSH_PAS }}" scp -r -o StrictHostKeyChecking=no ./backend/requirements.txt ./deploy/* ${{ secrets.SSH_USER }}@${{secrets.SSH_HOST}}:${{ secrets.BASE_DIR_APP }}build
    - name: Build Image
      run: |
            sshpass -p "${{ secrets.SSH_PAS }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{secrets.SSH_HOST}} << EOF
            ssh local <<-'EOF2'
                cd ${{ secrets.BASE_DIR_APP }}build/ \
                && ${{ secrets.BASE_DIR_OPS }}iptables -t mangle -F PREROUTING \
                && docker build . -t dj:latest \
                && ${{ secrets.BASE_DIR_OPS }}iptables.sh \
                && docker-compose -f ${{ secrets.BASE_DIR_OPS }}compose/app/app_compose.yaml up -d
            EOF2
            EOF