name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# env:
#   DATABASE_NAME: test
#   DATABASE_HOST: 127.0.0.1
#   DATABASE_PORT: 27017
#   DATABASE_USER: demo
#   DATABASE_PASS: passdemo
#   SECRET_KEY: 01h59f3xkpm!7%^=l)&)ti%#dq(t^986ax9md%zl27v9_!*dpp7

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt